#!/bin/bash

# AI Daily News - GitHub部署脚本
# 使用方法: ./deploy.sh YOUR_GITHUB_TOKEN

set -e

# 检查参数
if [ -z "$1" ]; then
    echo "❌ 错误: 请提供GitHub Personal Access Token"
    echo ""
    echo "使用方法: ./deploy.sh YOUR_GITHUB_TOKEN"
    echo ""
    echo "创建Token步骤:"
    echo "1. 访问 https://github.com/settings/tokens"
    echo "2. 点击 'Generate new token (classic)'"
    echo "3. Note: 'AI Daily News Deployment'"
    echo "4. 勾选: repo, workflow"
    echo "5. 复制token并运行脚本"
    exit 1
fi

TOKEN=$1
REPO_NAME="ai-daily-news"
GITHUB_USER="dontyhe13"
EMAIL="dontyhe13@gmail.com"

echo "🚀 开始部署AI Daily News到GitHub..."
echo "📦 仓库名: $REPO_NAME"
echo "👤 用户: $GITHUB_USER"

# 1. 检查是否已初始化Git
if [ ! -d .git ]; then
    echo "📝 初始化Git仓库..."
    git init
    git config user.name "$GITHUB_USER"
    git config user.email "$EMAIL"
else
    echo "✅ Git仓库已存在"
fi

# 2. 切换到main分支
echo "🌿 切换到main分支..."
git branch -M main

# 3. 创建GitHub仓库（使用API）
echo "🏗️ 创建GitHub仓库..."

# 检查仓库是否已存在
RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: token $TOKEN" \
    "https://api.github.com/repos/$GITHUB_USER/$REPO_NAME")

if [ "$RESPONSE" = "200" ]; then
    echo "⚠️ 仓库 $REPO_NAME 已存在，跳过创建"
else
    # 创建仓库
    curl -s -X POST \
        -H "Authorization: token $TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        -d "{\"name\":\"$REPO_NAME\",\"description\":\"AI Daily News - 每日AI新闻网站\",\"private\":false,\"auto_init\":false}" \
        "https://api.github.com/user/repos"

    if [ $? -eq 0 ]; then
        echo "✅ GitHub仓库创建成功"
    else
        echo "❌ 创建仓库失败"
        exit 1
    fi
fi

# 4. 添加远程仓库
echo "🔗 添加远程仓库..."
git remote remove origin 2>/dev/null || true
git remote add origin "https://$GITHUB_USER:$TOKEN@github.com/$GITHUB_USER/$REPO_NAME.git"

# 5. 添加并提交文件
echo "📤 提交文件..."
git add -A

# 检查是否有更改
if git diff --cached --quiet; then
    echo "⚠️ 没有新文件需要提交"
else
    echo "✍️ 提交更改..."
    git commit -m "✨ Initial commit: AI Daily News website

- 📰 每日AI新闻模块
- 📚 最新论文展示
- 🛠️ AI工具推荐
- 🔍 搜索和筛选功能
- 🌙 深色模式支持
- 📱 响应式设计
- 🚀 Vercel部署配置

🤖 Generated by javas"
fi

# 6. 推送到GitHub
echo "🚀 推送到GitHub..."
git push -u origin main

# 7. 完成
echo ""
echo "✅ 部署完成！"
echo ""
echo "📋 下一步操作:"
echo "1. 访问 https://vercel.com/new"
echo "2. 选择导入 '$REPO_NAME' 仓库"
echo "3. 点击 'Deploy' 自动部署"
echo ""
echo "🌐 部署成功后访问:"
echo "   https://dontyhe13.github.io/$REPO_NAME"
echo "   或"
echo "   https://$REPO_NAME.vercel.app"
echo ""
echo "🐈‍⬛ 恭喜！AI Daily News已上线！"
